-- Crear Base de Datos dbCurso
CREATE DATABASE dbCurso
DEFAULT CHARACTER SET utf8;

-- Poner en uso

USE dbCurso;

CREATE TABLE PERSONA
(
	DNIPER CHAR(8),
    NOMPER VARCHAR(50) null,
    APEPER VARCHAR (80) null,
    FECNACPER DATE null,
    CELPER CHAR (9) NULL,
    EMAPER VARCHAR (100),
    SEXPER CHAR(1) null,
    TIPPER CHAR(3) null,
    DISTPER VARCHAR(80) null,
    FECREGPER timestamp,
    PWSPER VARCHAR(20),
	CONSTRAINT DNIPER_PK PRIMARY KEY (DNIPER)     
);	


CREATE TABLE DEPARTAMENTO
(
	IDDEP INT,
    NOMDEP VARCHAR(50) null,
    DNIPER CHAR(8),
    SALJEFDEP DECIMAL(8,2),
	CONSTRAINT IDDEP_PK PRIMARY KEY (IDDEP)     
);	
SHOW TABLES;
ALTER TABLE DEPARTAMENTO
ADD CONSTRAINT PERSONA_DEPARTAMENTO_DNIPER
FOREIGN KEY (DNIPER) REFERENCES PERSONA (DNIPER);

SELECT * 
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
WHERE table_schema="dbCurso" 
    AND constraint_type="FOREIGN KEY";

